name: Java CI
on:
  push:
  workflow_dispatch:
jobs:
  build:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_USERNAME: ${{ secrets.GITHUB_USERNAME }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 15
      uses: actions/setup-java@v1
      with:
        java-version: 15
    - name: Setup VM
      run: |
        sudo apt-get update
        sudo apt-get install -y dbus-x11 libgconf-2-4
        sudo /usr/bin/Xvfb :99 -screen 0 1024x768x24 &
        sudo apt-get install -y firefox
        sudo apt-get install -y libappindicator1 fonts-liberation libgbm1
        # A fixed version of chrome, which we can pair a fixed version of chrome driver to
        wget https://octopus-guides.s3.amazonaws.com/chrome/google-chrome-stable_current_amd64.deb
        #wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        #wget https://dl.google.com/linux/direct/google-chrome-beta_current_amd64.deb
        #wget https://dl.google.com/linux/direct/google-chrome-unstable_current_amd64.deb
        sudo dpkg -i google-chrome*.deb
        wget https://chromedriver.storage.googleapis.com/87.0.4280.20/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo cp chromedriver /usr/local/bin
        sudo chmod +x /usr/local/bin/chromedriver
        wget https://github.com/mozilla/geckodriver/releases/download/v0.28.0/geckodriver-v0.28.0-linux64.tar.gz
        tar -xzf geckodriver-v0.28.0-linux64.tar.gz
        sudo cp geckodriver /usr/local/bin
        sudo chmod +x /usr/local/bin/geckodriver
    - name: Check for updates
      run: mvn versions:display-dependency-updates
    - name: Reattach HEAD
      run: git checkout "$(echo ${{ github.ref }} | sed -E 's|refs/[a-zA-Z]+/||')"
    - name: Set version
      run: mvn versions:set -DnewVersion=0.2.${GITHUB_RUN_NUMBER}
    - name: Build with Maven
      run: mvn package -DskipTests
    - name: Test
      run: mvn test
      env:
        DISPLAY: ":99.0"
        BROWSERSTACK_KEY: ${{ secrets.BROWSERSTACK_KEY }}
        BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
        CHROME_BIN: /usr/bin/google-chrome
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/webdriver:0.2.${GITHUB_RUN_NUMBER}
        docker tag ${{ secrets.DOCKER_USERNAME }}/webdriver:0.2.${GITHUB_RUN_NUMBER} ${{ secrets.DOCKER_USERNAME }}/webdriver:latest
    - name: Docker login
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    - name: Push the Docker image
      run: |
        docker push docker.io/${{ secrets.DOCKER_USERNAME }}/webdriver:0.2.${GITHUB_RUN_NUMBER}
        docker push docker.io/${{ secrets.DOCKER_USERNAME }}/webdriver:latest
    - name: Deploy to Github Package Registry
      run: |
        echo "<settings><servers><server><id>github</id><username>${GITHUB_USERNAME}</username><password>${GITHUB_TOKEN}</password></server></servers></settings>" > ~/.m2/settings.xml
        mvn deploy -X -DskipTests
